name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the XKP Docker image
      run: docker build . --file Dockerfile --tag xkp-dash-app:$(date +%s)
